### ISSUE TITLE
Default font style of the paper generated is different from IEEE default font style

### ISSUE THREAD

**Issue by prasadanjangi** [org-arl/jupyter-ieee-paper#1]
The `paper.tex` generated uses the following font style `\usepackage{mathpazo}`. However, for the times new roman which is the recommended font style for IEEE paper, we should use `\usepackage{mathptmx}`. Changing this in latex file works but could not figure out a way to set this in notebook metadata so that by default the paper is generated with the correct font style.

**Comment by mchitre** [comment]
Fixed
